# Generated by Django 5.0.6 on 2024-07-20 17:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                ("family_id", models.AutoField(primary_key=True, serialize=False)),
                ("family_name", models.CharField(max_length=50)),
                ("creation_date", models.DateField(default=datetime.date.today)),
                ("suggestion_deadline", models.TimeField(default="14:00")),
                ("dinner_deadline", models.TimeField(default="17:00")),
            ],
        ),
        migrations.CreateModel(
            name="DinnerOptions",
            fields=[
                (
                    "dinner_options_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("ingredients", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cuisine_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("italian", "Italian"),
                            ("mexican", "Mexican"),
                            ("chinese", "Chinese"),
                            ("indian", "Indian"),
                            ("japanese", "Japanese"),
                            ("american", "American"),
                            ("french", "French"),
                            ("mediterranean", "Mediterranean"),
                            ("thai", "Thai"),
                            ("greek", "Greek"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("home_entree", "Home Entree"),
                            ("restaurant", "Restaurant"),
                            ("delivery_option", "Delivery Option"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "family_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatisfordinner.family",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "family_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatisfordinner.family",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="family",
            name="admin_member_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="whatisfordinner.member",
            ),
        ),
        migrations.CreateModel(
            name="DinnerSuggestions",
            fields=[
                (
                    "dinner_suggestion_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_final_choice", models.BooleanField(default=False)),
                (
                    "dinner_options_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatisfordinner.dinneroptions",
                    ),
                ),
                (
                    "family_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatisfordinner.family",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whatisfordinner.member",
                    ),
                ),
            ],
        ),
    ]
